FROM node:16-alpine3.15 as build

WORKDIR /usr/front-chat/app

RUN yarn global add @nestjs/cli

COPY package.json .

RUN yarn install

COPY . .

RUN yarn build

FROM node:16-alpine3.15

WORKDIR /usr/front-chat/app

COPY --from=build /usr/front-chat/app/node_modules ./node_modules
COPY --from=build /usr/front-chat/app/dist ./dist
COPY --from=build /usr/front-chat/app/package.json ./package.json

USER node

EXPOSE 3011 3000

ENTRYPOINT [ "yarn", "start:prod" ]
