FROM node:16-alpine3.15 as install-dependecies

WORKDIR /usr/front-chat/app

COPY package.json .

RUN yarn install

FROM node:16-alpine3.15 as build

WORKDIR /usr/front-chat/app

COPY --from=install-dependecies /usr/front-chat/app/node_modules ./node_modules

COPY . .

RUN yarn build

FROM nginx:stable-alpine as production-stage

COPY --from=build /usr/front-chat/app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
